[Icon Theme]
Name=Tangwaita
Comment=Tango styled Adwaita fullcolor icons and GNOME core app icons 
Example=folder
Inherits=Tango,gnome,Adwaita,hicolor

# Directory list
Directories=16x16/devices,16x16/emblems,16x16/mimetypes,16x16/places,scalable/core_apps,scalable/devices,scalable/extras/browsers,scalable/extras/gnome_apps,scalable/extras/legacy_apps,scalable/extras/mimetypes,scalable/mimetypes,scalable/places,scalable/status

[16x16/devices]
Context=Devices
Size=16
Type=Fixed

[16x16/emblems]
Context=Emblems
Size=16
Type=Fixed

[16x16/mimetypes]
Context=MimeTypes
Size=16
Type=Fixed

[16x16/places]
Context=Places
Size=16
Type=Fixed

[scalable/core_apps]
Context=Applications
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/extras/browsers]
Context=Applications
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/extras/gnome_apps]
Context=Applications
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/extras/legacy_apps]
Context=Applications
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/extras/mimetypes]
Context=MimeTypes
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=128
MinSize=8
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=128
MinSize=8
MaxSize=512
Type=Scalable
